name: openbaptisthymnal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.2
  logging: ^1.2.0
  fvm: ^4.0.5
  toastification: ^3.0.3
  vector_graphics: ^1.1.19
  auto_size_text: ^3.0.0
  lottie: ^3.3.2
  liquid_glass_renderer: ^0.2.0-dev.3
  auto_route: ^10.1.2
  shared_preferences: ^2.5.4
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  image: ^4.7.2
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  vector_graphics_compiler: ^1.1.19
  auto_route_generator: ^10.1.2
  analyzer: ^7.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/hymnal/
    - assets/hymnal/languages/
    - assets/images/lottie/
    - path: assets/images/icons/
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EBGaramond-Regular.ttf
        - asset: assets/fonts/EBGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/EBGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/EBGaramond-Italic.ttf
          style: italic
        - asset: assets/fonts/EBGaramond-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/EBGaramond-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/EBGaramond-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist-Thin.ttf
          weight: 100
